### ISSUE TITLE
请问有在epoch1 training: 0%卡住的情况吗？

### ISSUE THREAD

**Issue by Tsuredur** [jyrao/MatchTime#2]
调整了batch_size和num_workers还是卡住了。用的A6000。

**Comment by jyrao** [comment]
可以先确保一下，整个model都已经move到cuda上，排除model的问题。可以把model或者train代码里面如果有try except的block。把它去掉，看一看报错。我之前没碰到过这样的问题。A6000的显存，应该能支撑小batchsize的运行。

**Comment by jyrao** [comment]
是否有尝试像我说的把try except给删掉，看看具体报错内容。以及是否确保model和data全在同一个device。你可以把具体显示的报错发上来看一下。

**Comment by Tsuredur** [comment]
> 是否有尝试像我说的把try except给删掉，看看具体报错内容。以及是否确保model和data全在同一个device。你可以把具体显示的报错发上来看一下。

你好，这个问题很早就已经解决，感谢回复。昨晚是close issue了。

**Comment by jyrao** [comment]
okok，那就好。多谢对我们项目的支持和follow😁
